### ISSUE TITLE
preserve directory loc

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcointranscripts/transcription-review-front-end#186]
the loc path should be preserved if:
- user exits the directory selector
- user clicks restore button

if a user opens the change directory, navigates a bit, and closes that menu without selecting a location, the saved directory path should persist. In this case that would be the `loc` path.

**Comment by kouloumos** [comment]
Trying to review the linked PR, I am not sure what the goal is here, so I am writing a scenario in order to better help me understand what this change looks like:
The user starts reviewing a transcript, that transcript has an original location (`loc`). The user changes that original `loc`. What happens when "Restore Original" is clicked? Does `loc` restores back to the original `loc`? It seems to me that in the description of this issue you wrote the opposite: that `loc` should be preserved if `Restore Original` is clicked.

I think my misunderstanding is with what you mean when you say "the loc path should be preserved". With preserved, you mean preserve the original?

**Comment by Emmanuel-Develops** [comment]
> Trying to review the linked PR, I am not sure what the goal is here, so I am writing a scenario in order to better help me understand what this change looks like: The user starts reviewing a transcript, that transcript has an original location (`loc`). The user changes that original `loc`. What happens when "Restore Original" is clicked? Does `loc` restores back to the original `loc`? It seems to me that in the description of this issue you wrote the opposite: that `loc` should be preserved if `Restore Original` is clicked.
> 
> I think my misunderstanding is with what you mean when you say "the loc path should be preserved". With preserved, you mean preserve the original?

So transcripts have two data sources `content` and `originalContent`.
`content` and `originalContent` are the same when a transcript is newly added to the queue i.e on `createTranscript` route.

subsequent user editing modifies the `content` field and the editor uses `content` as the source of truth.

When I use `preserve loc` i'm speaking relative to `content loc field` so if the user doesn't select (using the select button) any loc in the dropdown and exits the dropdown, we should preserve the `content loc`.

I can now see how the second list `click restore button` may be misleading.
I explained the issue to @0tuedon but yes the writing is misleading, it basically means in the current implementation, the restore original button doesn't reset the `loc` field. The restore original button should rewrite `content` with `originalContent` but factor in stale client-side state which was the issue.

**Comment by kouloumos** [comment]
> I can now see how the second list `click restore button` may be misleading. I explained the issue to @0tuedon but yes the writing is misleading, it basically means in the current implementation, the restore original button doesn't reset the `loc` field. The restore original button should rewrite `content` with `originalContent` but factor in stale client-side state which was the issue.

Thank you for the explanation, I now understand. `loc` not resetting is also one of the issues that I observed in #196.
