### ISSUE TITLE
when a review is expired, the transcript should be returned to the queue and able to be claimed by other reviewers

### ISSUE THREAD

**Issue by adamjonas** [bitcointranscripts/transcription-review-front-end#62]
This transcript should be back in the queue:

<img width="475" alt="Screen Shot 2023-05-15 at 12 47 38 PM" src="https://github.com/bitcointranscripts/transcription-review-front-end/assets/755825/053cad97-c397-48a6-88fb-909ca82de153">

**Comment by Emmanuel-Develops** [comment]
This is from the backend, I thought of CRON jobs to run this when the transcripts expire, but @nassersaazi gave a better suggestion for sleeper functions

I'll be taking that up next.

By the way users would not see expired reviews in their current reviews anymore, it will show up in their past review. But it is still possible to manually enter the url e.g `/reviews/8` to get to that review.

What should the frontend do in this situation? Prevent them from seeing the review all together, or disable the buttons i.e save, submit and revert to original?

**Comment by adamjonas** [comment]
The long term way to handle is to populate an archived_at field on the review and then disable the route if there is a timestamp present. 

Making the user manually enter it is enough friction for now though.

**Comment by Emmanuel-Develops** [comment]
I'm not too clear on the archivedAt. Does that happen for expired reviews? or purposefully closed reviews(doesn't exist yet)?

If it is expired it won't show up in the current review table, hence no review button to click and get back to. There was a bug with how I inferred it on the backend which was why you could still find the past review in current reviews. I have merged the fix for that so it shouldn't be there anymore.

**Comment by Emmanuel-Develops** [comment]
Closed by: https://github.com/bitcointranscripts/transcription-review-backend/pull/41
